version: '3'

networks:
  am:
    ipam:
      driver: default

services:

  node-eve:
    image: ghcr.io/digicatapult/vitalam-node:v2.9.3
    container_name: node-eve
    command:
      --base-path /data/
      --eve
      --node-key ${NODE_EVE_KEY}
      --bootnodes /dns4/node-bob/tcp/30333/p2p/${NODE_BOB_PEERID}
      --chain local
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors all
    ports:
      - 30336:30333
      - 9947:9944
      - 9936:9933
    volumes:
      - ../data/am-lab/node:/data
    restart: on-failure
    networks: ['am']

  ipfs-eve:
    image: ghcr.io/digicatapult/vitalam-ipfs:v1.2.9
    container_name: ipfs-eve
    ports:
      - 5004:5001
      - 4004:4001
    volumes:
      - ../data/am-lab/ipfs:/ipfs
    environment:
      - NODE_HOST=node-eve
    restart: on-failure
    networks: ['am']

  api-eve:
    image: ghcr.io/digicatapult/vitalam-api:v2.9.0
    container_name: api-eve
    ports:
      - 3004:3001
    environment:
      - PORT=3001
      - API_HOST=node-eve
      - API_PORT=9944
      - USER_URI=${API_EVE_WALLET_USER_URI}
      - IPFS_HOST=ipfs-eve
      - IPFS_PORT=5001
      - LOG_LEVEL=debug
      - AUTH_JWKS_URI=${API_JWKS_URI}
      - AUTH_AUDIENCE=${API_AUTH_AUDIENCE}
      - AUTH_ISSUER=${API_AUTH_ISSUER}
      - AUTH_TOKEN_URL=${API_AUTH_TOKEN_URL}
    restart: on-failure
    networks: ['am']

  react-eve:
    container_name: react-eve
    build:
      context: '../'
      dockerfile: 'Dockerfile'
      args:
        - REACT_APP_VITALAM_DEMO_PERSONA=amlab
        - REACT_APP_API_HOST=${REACT_API_EVE_HOST}
        - REACT_APP_API_PORT=${REACT_API_EVE_PORT}
        - REACT_APP_SUBSTRATE_HOST=${REACT_API_EVE_SUBSTRATE_HOST}
        - REACT_APP_SUBSTRATE_PORT=${REACT_API_EVE_SUBSTRATE_PORT}
        - REACT_APP_AUTH_CLIENT_ID=${REACT_API_AUTH_CLIENT_ID}
        - REACT_APP_AUTH_CLIENT_SECRET=${REACT_API_AUTH_CLIENT_SECRET}
    ports:
      - 8004:80
    restart: on-failure
    networks: ['am']
