version: '3'

networks:
  chain:
    ipam:
      driver: default
  ipfs:
    ipam:
      driver: default
  am:
    ipam:
      driver: default

services:
  node-bob:
    image: ghcr.io/digicatapult/vitalam-node:v2.7.0
    container_name: node-bob
    command:
      --base-path /data/
      --bob
      --node-key ${NODE_BOB_KEY}
      --bootnodes /dns4/node-alice/tcp/30333/p2p/${NODE_ALICE_PEERID}
      --bootnodes /dns4/node-charlie/tcp/30333/p2p/${NODE_CHARLIE_PEERID}
      --chain local
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors all
    ports:
      - 30334:30333
      - 9945:9944
      - 9934:9933
    volumes:
      - ../data/am/node:/data
    restart: on-failure
    networks: ['chain', 'am']

  ipfs-bob:
    image: ghcr.io/digicatapult/vitalam-ipfs:v1.1.0
    container_name: ipfs-bob
    ports:
      - 5002:5001
      - 4002:4001
    volumes:
      - ../data/am/ipfs:/ipfs
    environment:
      - NODE_HOST=node-bob
    restart: on-failure
    networks: ['ipfs', 'am']

  api-bob:
    image: ghcr.io/digicatapult/vitalam-api:v2.6.2
    container_name: api-bob
    ports:
      - 3002:3001
    environment:
      - PORT=3001
      - API_HOST=node-bob
      - API_PORT=9944
      - USER_URI=${API_BOB_WALLET_USER_URI}
      - IPFS_HOST=ipfs-bob
      - IPFS_PORT=5001
      - LOG_LEVEL=debug
      - AUTH_JWKS_URI=${API_JWKS_URI}
      - AUTH_AUDIENCE=${API_AUTH_AUDIENCE}
      - AUTH_ISSUER=${API_AUTH_ISSUER}
      - AUTH_TOKEN_URL=${API_AUTH_TOKEN_URL}
    restart: on-failure
    networks: ['am']

  react-bob:
    container_name: react-bob
    build:
      context: '../'
      dockerfile: 'Dockerfile'
      args:
        - REACT_APP_VITALAM_DEMO_PERSONA=am
        - REACT_APP_API_HOST=${REACT_API_BOB_HOST}
        - REACT_APP_API_PORT=${REACT_API_BOB_PORT}
        - REACT_APP_SUBSTRATE_HOST=${REACT_API_BOB_SUBSTRATE_HOST}
        - REACT_APP_SUBSTRATE_PORT=${REACT_API_BOB_SUBSTRATE_PORT}
        - REACT_APP_AUTH_CLIENT_ID=${REACT_API_AUTH_CLIENT_ID}
        - REACT_APP_AUTH_CLIENT_SECRET=${REACT_API_AUTH_CLIENT_SECRET}
    ports:
      - 8002:3000
    restart: on-failure
    networks: ['am']
