version: '3'

networks:
  chain:
    ipam:
      driver: default
  ipfs:
    ipam:
      driver: default
  lab:
    ipam:
      driver: default

services:
  node-charlie:
    image: ghcr.io/digicatapult/vitalam-node:v2.9.3
    container_name: node-charlie
    command:
      --base-path /data/
      --charlie
      --node-key ${NODE_CHARLIE_KEY}
      --bootnodes /dns4/node-alice/tcp/30333/p2p/${NODE_ALICE_PEERID}
      --bootnodes /dns4/node-bob/tcp/30333/p2p/${NODE_BOB_PEERID}
      --chain local
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors all
    ports:
      - 30335:30333
      - 9946:9944
      - 9935:9933
    volumes:
      - ../data/lab/node:/data
    restart: on-failure
    networks: ['chain', 'lab']

  ipfs-charlie:
    image: ghcr.io/digicatapult/vitalam-ipfs:v1.2.9
    container_name: ipfs-charlie
    ports:
      - 5003:5001
      - 4003:4001
    volumes:
      - ../data/lab/ipfs:/ipfs
    environment:
      - NODE_HOST=node-charlie
    restart: on-failure
    networks: ['ipfs', 'lab']

  api-charlie:
    image: ghcr.io/digicatapult/vitalam-api:v2.9.0
    container_name: api-charlie
    ports:
      - 3003:3001
    environment:
      - PORT=3001
      - API_HOST=node-charlie
      - API_PORT=9944
      - USER_URI=${API_CHARLIE_WALLET_USER_URI}
      - IPFS_HOST=ipfs-charlie
      - IPFS_PORT=5001
      - LOG_LEVEL=debug
      - AUTH_JWKS_URI=${API_JWKS_URI}
      - AUTH_AUDIENCE=${API_AUTH_AUDIENCE}
      - AUTH_ISSUER=${API_AUTH_ISSUER}
      - AUTH_TOKEN_URL=${API_AUTH_TOKEN_URL}
    restart: on-failure
    networks: ['lab']

  react-charlie:
    container_name: react-charlie
    build:
      context: '../'
      dockerfile: 'Dockerfile'
      args:
        - REACT_APP_VITALAM_DEMO_PERSONA=lab
        - REACT_APP_API_HOST=${REACT_API_CHARLIE_HOST}
        - REACT_APP_API_PORT=${REACT_API_CHARLIE_PORT}
        - REACT_APP_SUBSTRATE_HOST=${REACT_API_CHARLIE_SUBSTRATE_HOST}
        - REACT_APP_SUBSTRATE_PORT=${REACT_API_CHARLIE_SUBSTRATE_PORT}
        - REACT_APP_AUTH_CLIENT_ID=${REACT_API_AUTH_CLIENT_ID}
        - REACT_APP_AUTH_CLIENT_SECRET=${REACT_API_AUTH_CLIENT_SECRET}
    ports:
      - 8003:80
    restart: on-failure
    networks: ['lab']
